[versions]
indra = '4.0.0'
jmh = '1.37'

[plugins]
indra-publishing = { id = 'net.kyori.indra.publishing', version.ref = 'indra' }
indra-publishing-sonatype = { id = 'net.kyori.indra.publishing.sonatype', version.ref = 'indra' }

jmh = 'me.champeau.jmh:0.7.3'

[libraries]
jmh-core = { module = 'org.openjdk.jmh:jmh-core', version.ref = 'jmh' }
jmh-generator-annprocess = { module = 'org.openjdk.jmh:jmh-generator-annprocess', version.ref = 'jmh' }

yunan9-commons = 'io.github.yunan9:commons:0.1.3-SNAPSHOT'
jetbrains-annotations = 'org.jetbrains:annotations:26.0.2-1'